spring.application.name=demo
server.port=8080

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./data/agendaqui
spring.datasource.username=sa
spring.datasource.password=

# Configuracoes JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracoes H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL logging
logging.level.org.hibernate.SQL=DEBUG